server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 889400312069-ho7mpmpav535ans4ctot6j1urcu0493e.apps.googleusercontent.com
            client-secret: pcocN7-v-LRUDxJM7l3HOdJb
            scope:
            - email
            - profile
            
          facebook:
            client-id: 178114604300548
            client-secret: eea49015f89491c7008127bbf9fd2f57
            scope:
            - email
            - public_profile
            
          naver:
            client-id: U9EtEKI1I75tv9gpcoJh
            client-secret: I9MQPZuxDo
            scope:
            - name
            - email
            #- profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver #구글, 페이스북은 기본적으로 설정되어 있음.
            
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.
            